<a href="https://colab.research.google.com/github/iamsachinbagale/PyTorch-Tutorial/blob/main/Intro_to_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.3.0+cu121'

# LISTS

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAY

In [6]:
import numpy as np

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.63758713, 0.09312332, 0.0511328 , 0.46913373],
       [0.46490614, 0.15757814, 0.99660498, 0.11179384],
       [0.28244474, 0.0614699 , 0.42776982, 0.87818945]])

# TENSORS

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.0742, -0.0062, -0.7357,  1.1023],
        [-1.2119,  0.0665,  1.2670,  0.0792],
        [-0.0934, -0.2511,  1.2057, -0.0151]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6376, 0.0931, 0.0511, 0.4691],
        [0.4649, 0.1576, 0.9966, 0.1118],
        [0.2824, 0.0615, 0.4278, 0.8782]], dtype=torch.float64)

In [14]:
my_tensor.dtype

torch.float64