<a href="https://colab.research.google.com/github/iamsachinbagale/PyTorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR MATH OPERATION**
* Add, Subtract, Mulitple, Divide, Remainders, Exponents
* Shorthand and Longhand
* Reassignment

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
#Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [10]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
#Mul Function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Remainder Modulus
tensor_b  & tensor_a

tensor([1, 2, 3, 0])

In [19]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [21]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [22]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_b.sub(tensor_a)

tensor([4, 4, 4, 4])

In [24]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [25]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
# tensor_a = tensor_a + tensor_b
 tensor_a.add_(tensor_b)     #underscore is used to reassign

tensor([ 6,  8, 10, 12])

In [27]:
tensor_a

tensor([ 6,  8, 10, 12])